### ISSUE TITLE
Include project links in pyproject.toml

### ISSUE THREAD

**Issue by jorgepiloto** [DSAV-code/similator#1]
I found this package directly in PyPI. However, it was a bit tricky to find it in GitHub since no project URLs are listed.

It is possible to add these links in the `pyproject.toml` like this:

```toml
[project.urls]
source = "https://github.com/DSAV-code/similator/"
issues = "https://github.com/DSAV-code/similator/issues/"
Releases = "https://github.com/DSAV-code/similator/releases"
```
